---
hostname: SW2

management_ip: 172.16.2.2
management_mask: 255.255.255.0
management_interface: Vlan20

uplink_interface: GigabitEthernet1/0/2
laptop_interface: GigabitEthernet1/0/4
device_type: switch

interface_description: Link til R2

vlans:
  - id: 20
    name: STUD2
