---
- name: Konfigurer access-porter
  hosts: cisco
  gather_facts: false

  tasks:
    - name: Sett access-port og VLAN
      cisco.ios.ios_config:
        parents:
          - "interface {{ item.interface }}"
        lines:
          - switchport mode access
          - "switchport access vlan {{ item.vlan }}"
          - spanning-tree portfast
      loop: "{{ access_ports | default([]) }}"
      when: device_type == "switch"
